### ISSUE TITLE
ezdesign name space fails on first load

### ISSUE THREAD

**Issue by wizhippo** [ezsystems/ezplatform-design-engine#2]
With the settings:

```
ezpublish:
    system:
        site_group:
            design: testdesign

ezdesign:
      design_list:
          testdesign: [testdesign]

system:
    default:
        content_view:
            full:
                home_page:
                    template: "@ezdesign/full/home_page.html.twig"
                    controller: ConsumerSiteBundle:ConsumerSite:homePageView
                    match:
                        Identifier\ContentType: [home_page]

```
On a clean cache I get

`Unable to find template "@standard/full/home_page.html.twig"`

On reload I get the correct page.  Looks like "$design$" is incorrect when the container builds the cacheWarmerService and in turn builds the twig loader service.  Perhaps siteaccess is not matched before cache warming?
